-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 13:52:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Components
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Components
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Components` DEFAULT CHARACTER SET utf8 ;
USE `Components` ;

-- -----------------------------------------------------
-- Table `Components`.`compdescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Components`.`compdescription` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ComponentType` VARCHAR(128) NULL,
  `ManufacturerPartNumber` VARCHAR(255) NULL,
  `Value` FLOAT NULL,
  `Power/Voltage` FLOAT NULL,
  `Case` VARCHAR(64) NULL,
  `Tolerance` FLOAT NULL,
  `Note` VARCHAR(255) NULL,
  `Manufacturer` VARCHAR(128) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
