-- MySQL Script generated by MySQL Workbench
-- Tue Jul  7 08:58:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema components
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema components
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `components` DEFAULT CHARACTER SET utf8 ;
USE `components` ;

-- -----------------------------------------------------
-- Table `components`.`compdescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `components`.`compdescription` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ComponentType` VARCHAR(128) NULL DEFAULT NULL,
  `ManufacturerPartNumber` VARCHAR(255) NULL DEFAULT NULL,
  `Value` FLOAT NULL DEFAULT NULL,
  `Unit` VARCHAR(45) NULL DEFAULT NULL,
  `Tolerance` FLOAT NULL DEFAULT NULL,
  `Power/Voltage` FLOAT NULL DEFAULT NULL,
  `Case` VARCHAR(64) NULL DEFAULT NULL,
  `Manufacturer` VARCHAR(128) NULL DEFAULT NULL,
  `Quantity` INT UNSIGNED NOT NULL DEFAULT '1',
  `Note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
